// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' };
import * as $0 from './routes/[name].tsx';
import * as $1 from './routes/about.tsx';
import * as $2 from './routes/api/email.ts';
import * as $3 from './routes/api/joke.ts';
import * as $4 from './routes/api/reservation.ts';
import * as $5 from './routes/api/spots.ts';
import * as $6 from './routes/contact.tsx';
import * as $7 from './routes/dashboard.tsx';
import * as $8 from './routes/dashboard/[slug].tsx';
import * as $9 from './routes/dashboard/home.tsx';
import * as $10 from './routes/dashboard/test.tsx';
import * as $11 from './routes/index.tsx';
import * as $12 from './routes/login.tsx';
import * as $13 from './routes/places.tsx';
import * as $14 from './routes/places/[slug].tsx';
import * as $15 from './routes/reservation.tsx';
import * as $16 from './routes/reservation/[slug].tsx';
import * as $17 from './routes/reset.tsx';
import * as $18 from './routes/services.tsx';
import * as $19 from './routes/test.tsx';
import * as $20 from './routes/upload.tsx';
import * as $$0 from './islands/About-Services.tsx';
import * as $$1 from './islands/About-Us.tsx';
import * as $$2 from './islands/Add-Place.tsx';
import * as $$3 from './islands/Agreement.tsx';
import * as $$4 from './islands/Contact-Us.tsx';
import * as $$5 from './islands/Counter.tsx';
import * as $$6 from './islands/Instruction.tsx';
import * as $$7 from './islands/OTP-Form.tsx';
import * as $$8 from './islands/Place.tsx';
import * as $$9 from './islands/Posts.tsx';
import * as $$10 from './islands/Reservation-Form.tsx';
import * as $$11 from './islands/Reservation-Stepper.tsx';
import * as $$12 from './islands/Reservations.tsx';
import * as $$13 from './islands/Spots.tsx';
import * as $$14 from './islands/Team-Members.tsx';

const manifest = {
	routes: {
		'./routes/[name].tsx': $0,
		'./routes/about.tsx': $1,
		'./routes/api/email.ts': $2,
		'./routes/api/joke.ts': $3,
		'./routes/api/reservation.ts': $4,
		'./routes/api/spots.ts': $5,
		'./routes/contact.tsx': $6,
		'./routes/dashboard.tsx': $7,
		'./routes/dashboard/[slug].tsx': $8,
		'./routes/dashboard/home.tsx': $9,
		'./routes/dashboard/test.tsx': $10,
		'./routes/index.tsx': $11,
		'./routes/login.tsx': $12,
		'./routes/places.tsx': $13,
		'./routes/places/[slug].tsx': $14,
		'./routes/reservation.tsx': $15,
		'./routes/reservation/[slug].tsx': $16,
		'./routes/reset.tsx': $17,
		'./routes/services.tsx': $18,
		'./routes/test.tsx': $19,
		'./routes/upload.tsx': $20,
	},
	islands: {
		'./islands/About-Services.tsx': $$0,
		'./islands/About-Us.tsx': $$1,
		'./islands/Add-Place.tsx': $$2,
		'./islands/Agreement.tsx': $$3,
		'./islands/Contact-Us.tsx': $$4,
		'./islands/Counter.tsx': $$5,
		'./islands/Instruction.tsx': $$6,
		'./islands/OTP-Form.tsx': $$7,
		'./islands/Place.tsx': $$8,
		'./islands/Posts.tsx': $$9,
		'./islands/Reservation-Form.tsx': $$10,
		'./islands/Reservation-Stepper.tsx': $$11,
		'./islands/Reservations.tsx': $$12,
		'./islands/Spots.tsx': $$13,
		'./islands/Team-Members.tsx': $$14,
	},
	baseUrl: import.meta.url,
	config,
};

export default manifest;
